### ISSUE TITLE
[Utfall]: Test av forskningsutfall

### ISSUE THREAD

**Issue by sorensensig** [digdir/insights-hub#1]
### Hva

Ingen innhold

### Hvor

Ingen innhold

### Hvem

Ingen innhold

### Eksempler

Ingen innhold

### Relevant forskning

Ingen innhold

### Relevant innsikt

Ingen innhold

### Media format

Annen type artefakt

### Tilgjengelig på språk

English / Engelsk, Norsk (bokmål)

**Comment by indiamaydesign** [comment]
This is an incredibly important report, but I would just like to point out some inaccuracies that jeg ikke forstår. 1) Hvor: ingen innhold - this is impossible as we must exist in some place at any given moment, 2) Tilgjengelig på språk - while you spelt English right the first time, you follow it immediately with a typo (Engelsk). Other than this it is a very good job.
